### ISSUE TITLE
Unble to require "upcast" using node

### ISSUE THREAD

**Issue by bhavinkamani** [OmgImAlexis/upcast#5]
I am unable to require `upcast` as module in node. This could be because in I don't see `main` entry within package.json.

Following does not work in node
```
var upcast = require("node");
```

**Comment by OmgImAlexis** [comment]
Why would that work? You're requiring `node` not `upcast`?

**Comment by bhavinkamani** [comment]
I am so sorry. I meant `var upcast = require("upcast")`. 

With just a normal `yarn add upcast`, I get following error
```
$ node
> var upcast = require("upcast");
Error: Cannot find module 'upcast'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
```

When I make a following entry to upcast's `package.json`

```
"main": "./dist/upcast.cjs.js",
```
node is able to recognise the module.
```
$ node
> var upcast = require("upcast");
undefined
> 
```

**Comment by OmgImAlexis** [comment]
Please update to `3.0.1`. This should have fixed it. https://github.com/OmgImAlexis/upcast/commit/bb9f2b9b763fbf6cefc6d31697de66109368e1c4

**Comment by bhavinkamani** [comment]
Thanks a ton.
